### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by BigDeepBlue** [agredyaev/Async_API_sprint_2#16]
Обратите внимание на:
1. В скриптах ожидания ES и Redis в тестах (`tests/functional/utils/wait_for_es.py` и `tests/functional/utils/wait_for_redis.py`) вместо вечного цикла, в который можно попасть при возникновении сложностей, лучше использовать backoff из прошлых спринтов. Он более функционален в сравнении с вечным циклом, теоретически он может сигнализировать команде поддержки после определенного количества попыток.
2. В тестах проверяете только статус и размер ответа. Это не очень хорошо. Мы должны гарантировать правильную выдачу. Т.е. ничего лишнего не должно попасть к пользователю и ничего не должны пропустить. Так что, хотя бы в паре тестов нужно проверить полностью результат.
3. [FYI] Вероятно, вам как сильной команде, будет интересно. Ни в коем случае не инструкция к действию, а просто к сведению. Реализация простейшего контейнера внедрения зависимостей (C#, php и много кто еще без них вообще из дома не выходят), https://github.com/RomanAVolodin/FastAPI_DI/tree/feature/DI, вся работа идет с абстрактными классами, которые выступают в роли интерфейсов, а сопоставление абстрактного класса и его реализации происходит в одном месте, и если будет принято решение использовать другую реализацию, то достаточно будет внести изменение в одном месте кода.

**Comment by agredyaev** [comment]
done

**Comment by BigDeepBlue** [comment]
LGTM
